import { IMenu } from './types';

export default [
    { name: '독도 도시락', price: 5500 },
    { name: '양평우렁 강된장쌈밥', price: 7000 },
    { name: '삼겹살 쌈밥도시락', price: 10000 },
    { name: '우삼겹 쌈밥도시락', price: 8000 },
    { name: '제육 쌈밥도시락', price: 7000 },
    { name: '소불고기 쌈밥도시락', price: 7500 },
    { name: '서울 도시락', price: 5600 },
    { name: '대전 도시락', price: 5800 },
    { name: '대구 도시락', price: 5600 },
    { name: '부산 도시락', price: 5600 },
    { name: '울산 도시락', price: 5800 },
    { name: '광주 도시락', price: 5800 },
    { name: '하와이안 스테이크 도시락', price: 9000 },
    { name: '훌리훌리 도시락', price: 7500 },
    { name: '육해공 도시락', price: 8000 },
    { name: '배꼽터진 왕돈까스 도시락', price: 6500 },
    { name: '목살 스테이크 도시락', price: 9000 },
    { name: '김치찌개세트', price: 5000 },
    { name: '육개장세트', price: 5000 },
    { name: '김치찌개 + 밥', price: 4000 },
    { name: '육개장 + 밥', price: 4000 },
] as IMenu[];
